// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/bridge_http.proto

package bridge_http

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	ReqType       string                 `protobuf:"bytes,4,opt,name=reqType,proto3" json:"reqType,omitempty"`
	Request       []byte                 `protobuf:"bytes,5,opt,name=request,proto3" json:"request,omitempty"`
	TokenFcm      string                 `protobuf:"bytes,6,opt,name=tokenFcm,proto3" json:"tokenFcm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitRequest) Reset() {
	*x = HitRequest{}
	mi := &file_proto_bridge_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitRequest) ProtoMessage() {}

func (x *HitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitRequest.ProtoReflect.Descriptor instead.
func (*HitRequest) Descriptor() ([]byte, []int) {
	return file_proto_bridge_http_proto_rawDescGZIP(), []int{0}
}

func (x *HitRequest) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *HitRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *HitRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *HitRequest) GetReqType() string {
	if x != nil {
		return x.ReqType
	}
	return ""
}

func (x *HitRequest) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *HitRequest) GetTokenFcm() string {
	if x != nil {
		return x.TokenFcm
	}
	return ""
}

type HitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      []byte                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitResponse) Reset() {
	*x = HitResponse{}
	mi := &file_proto_bridge_http_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitResponse) ProtoMessage() {}

func (x *HitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_http_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitResponse.ProtoReflect.Descriptor instead.
func (*HitResponse) Descriptor() ([]byte, []int) {
	return file_proto_bridge_http_proto_rawDescGZIP(), []int{1}
}

func (x *HitResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *HitResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HitResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *HitResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_proto_bridge_http_proto protoreflect.FileDescriptor

const file_proto_bridge_http_proto_rawDesc = "" +
	"\n" +
	"\x17proto/bridge_http.proto\x12\n" +
	"bridgeHTTP\"\xac\x01\n" +
	"\n" +
	"HitRequest\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x18\n" +
	"\areqType\x18\x04 \x01(\tR\areqType\x12\x18\n" +
	"\arequest\x18\x05 \x01(\fR\arequest\x12\x1a\n" +
	"\btokenFcm\x18\x06 \x01(\tR\btokenFcm\"\xe9\x01\n" +
	"\vHitResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\x12>\n" +
	"\aheaders\x18\x02 \x03(\v2$.bridgeHTTP.HitResponse.HeadersEntryR\aheaders\x12\"\n" +
	"\ferrorMessage\x18\x03 \x01(\tR\ferrorMessage\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x04 \x01(\x05R\n" +
	"statusCode\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012B\n" +
	"\x06PgCall\x128\n" +
	"\x05HitPg\x12\x16.bridgeHTTP.HitRequest\x1a\x17.bridgeHTTP.HitResponseB\x1fZ\x1dinternal/app/grpc/bridge_httpb\x06proto3"

var (
	file_proto_bridge_http_proto_rawDescOnce sync.Once
	file_proto_bridge_http_proto_rawDescData []byte
)

func file_proto_bridge_http_proto_rawDescGZIP() []byte {
	file_proto_bridge_http_proto_rawDescOnce.Do(func() {
		file_proto_bridge_http_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bridge_http_proto_rawDesc), len(file_proto_bridge_http_proto_rawDesc)))
	})
	return file_proto_bridge_http_proto_rawDescData
}

var (
	file_proto_bridge_http_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
	file_proto_bridge_http_proto_goTypes  = []any{
		(*HitRequest)(nil),  // 0: bridgeHTTP.HitRequest
		(*HitResponse)(nil), // 1: bridgeHTTP.HitResponse
		nil,                 // 2: bridgeHTTP.HitResponse.HeadersEntry
	}
)
var file_proto_bridge_http_proto_depIdxs = []int32{
	2, // 0: bridgeHTTP.HitResponse.headers:type_name -> bridgeHTTP.HitResponse.HeadersEntry
	0, // 1: bridgeHTTP.PgCall.HitPg:input_type -> bridgeHTTP.HitRequest
	1, // 2: bridgeHTTP.PgCall.HitPg:output_type -> bridgeHTTP.HitResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_bridge_http_proto_init() }
func file_proto_bridge_http_proto_init() {
	if File_proto_bridge_http_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bridge_http_proto_rawDesc), len(file_proto_bridge_http_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bridge_http_proto_goTypes,
		DependencyIndexes: file_proto_bridge_http_proto_depIdxs,
		MessageInfos:      file_proto_bridge_http_proto_msgTypes,
	}.Build()
	File_proto_bridge_http_proto = out.File
	file_proto_bridge_http_proto_goTypes = nil
	file_proto_bridge_http_proto_depIdxs = nil
}
